language: rust

rust:
  - stable
  - beta
  - nightly

script:
  - cargo build -v
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then cargo test -v; fi
  - |
    if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then
      rustup component add rustfmt
      cargo fmt --all -- --check
    fi
  - cargo doc -v

after_success:
  - curl http://docs.piston.rs/travis-doc-upload.sh | sh
